version: '3.8'

services:
  nginx:
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/public:/app/public:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fpm

  fpm:
    build:
      target: dev
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./api:/app:rw,cached

  node:
    build:
      target: dev
    user: ${USER_ID}:${GROUP_ID}
    environment:
      NODE_ENV: development
      APP_DIR: /var/www/app
    volumes:
      - ./client:/var/www/app:rw,cached
    command:
      - /bin/ash
      - -c
      - |
        npm install
        npm rebuild node-sass
        npm run serve
    ports:
      - "3000:3000"